//Componentes
//import AdminDashboard from "../../global-components/admin_dashboard"

//Recursos
import 'bootstrap/dist/css/bootstrap.min.css';
import VerifyComponent from '../global-components/verify_component';


export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">        
        <body>
            <VerifyComponent>{children}</VerifyComponent>
        </body>
      </html>
    )
  }