export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}



// 'use client';
// import React from 'react';
// import { BrowserRouter, Routes, Route } from 'react-router-dom';
// import Page from './page';
// import { PaymentMethodValidation } from './cart-validation/payment-method-validation';

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <div>
        
//       <BrowserRouter>
//         <Routes>
//           <Route path="/" element={<Page />} />
//           <Route path="/cart-validation/payment-method-validation" element={<PaymentMethodValidation />}
//         />
//         </Routes>
//       </BrowserRouter>
//     </div>
//   );
// }
//https://stackoverflow.com/questions/77077948/next-js-how-to-define-the-app-js-and-layout-tsx-file-well
//https://www.reddit.com/r/nextjs/comments/18veugz/whats_the_different_between_appjs_versus_layoutjs/
//https://nextjs.org/docs/app/api-reference/file-conventions/layout
//https://nextjs.org/docs/getting-started/project-structure