//Componentes
import AdminDashboard from "../../global-components/admin_dashboard"

//Recursos
import 'bootstrap/dist/css/bootstrap.min.css';
import './../../src/css/init_dashboard.css';
import './../../src/css/fonts_awesome/css/all.min.css'


export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">        
        <body>
          <AdminDashboard>
            {/* Aqui iria el contenido de las diferentes paginas que usen este layout, como reportes
            ,productos... etc
             */}
            {children}
          </AdminDashboard>          
        </body>
      </html>
    )
  }